## Deliverable 2. Create a Customer Travel Destinations Map.

In [2]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [12]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("../Weather_Database/WeatherPy_Database.csv")
city_data_df

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Bahia Blanca,AR,-38.7196,-62.2724,46.72,85,69,10.11,broken clouds
1,1,Mozarlandia,BR,-14.7447,-50.5706,71.80,31,0,3.98,clear sky
2,2,Avera,US,33.1940,-82.5271,81.91,57,52,8.86,broken clouds
3,3,San Miguel,SV,13.4833,-88.1833,82.06,83,20,5.75,few clouds
4,4,Mataura,NZ,-46.1927,168.8643,47.48,98,100,3.13,overcast clouds
...,...,...,...,...,...,...,...,...,...,...
213,213,Nova Olimpia,BR,-14.7972,-57.2881,73.45,37,0,3.29,clear sky
214,214,Rio Cuarto,AR,-33.1307,-64.3499,49.68,82,100,15.01,overcast clouds
215,215,Lircay,PE,-12.9896,-74.7205,47.08,70,34,1.74,scattered clouds
216,216,Cambui,BR,-22.6122,-46.0575,59.16,68,19,1.03,few clouds
217,217,Aracati,BR,-4.5617,-37.7697,78.19,68,98,8.79,overcast clouds

In [8]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
min_temp = float(input('What is the minimum temperature you would like for your trip? '))
max_temp = float(input('What is the maximum temperature you would like for your trip? '))

What is the minimum temperature you would like for your trip? 70
What is the maximum temperature you would like for your trip? 90

In [11]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
preferred_cities_df = city_data_df.loc[(city_data_df['Max Temp'] <= max_temp) &\
                                       (city_data_df['Max Temp'] >= min_temp)]
preferred_cities_df

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
1,1,Mozarlandia,BR,-14.7447,-50.5706,71.80,31,0,3.98,clear sky
2,2,Avera,US,33.1940,-82.5271,81.91,57,52,8.86,broken clouds
3,3,San Miguel,SV,13.4833,-88.1833,82.06,83,20,5.75,few clouds
7,7,Zorritos,PE,-3.6805,-80.6782,73.69,85,59,9.35,broken clouds
9,9,Rikitea,PF,-23.1203,-134.9692,74.03,68,100,15.84,overcast clouds
...,...,...,...,...,...,...,...,...,...,...
210,210,Maragogi,BR,-9.0122,-35.2225,71.98,88,69,4.94,broken clouds
211,211,Cururupu,BR,-1.8283,-44.8683,73.96,88,31,2.26,scattered clouds
212,212,Coahuayana,MX,18.7333,-103.6833,79.59,80,100,1.66,overcast clouds
213,213,Nova Olimpia,BR,-14.7972,-57.2881,73.45,37,0,3.29,clear sky
217,217,Aracati,BR,-4.5617,-37.7697,78.19,68,98,8.79,overcast clouds

In [13]:
# 4a. Determine if there are any empty rows.
preferred_cities_df.isnull().sum()

City_ID                0
City                   0
Country                0
Lat                    0
Lng                    0
Max Temp               0
Humidity               0
Cloudiness             0
Wind Speed             0
Current Description    0
dtype: int64

In [15]:
# 4b. Drop any empty rows and create a new DataFrame that doesnâ€™t have empty rows.
preferred_cities_df = preferred_cities_df.dropna()
preferred_cities_df

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
1,1,Mozarlandia,BR,-14.7447,-50.5706,71.80,31,0,3.98,clear sky
2,2,Avera,US,33.1940,-82.5271,81.91,57,52,8.86,broken clouds
3,3,San Miguel,SV,13.4833,-88.1833,82.06,83,20,5.75,few clouds
7,7,Zorritos,PE,-3.6805,-80.6782,73.69,85,59,9.35,broken clouds
9,9,Rikitea,PF,-23.1203,-134.9692,74.03,68,100,15.84,overcast clouds
...,...,...,...,...,...,...,...,...,...,...
210,210,Maragogi,BR,-9.0122,-35.2225,71.98,88,69,4.94,broken clouds
211,211,Cururupu,BR,-1.8283,-44.8683,73.96,88,31,2.26,scattered clouds
212,212,Coahuayana,MX,18.7333,-103.6833,79.59,80,100,1.66,overcast clouds
213,213,Nova Olimpia,BR,-14.7972,-57.2881,73.45,37,0,3.29,clear sky
217,217,Aracati,BR,-4.5617,-37.7697,78.19,68,98,8.79,overcast clouds

In [17]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
1,Mozarlandia,BR,71.80,clear sky,-14.7447,-50.5706,
2,Avera,US,81.91,broken clouds,33.1940,-82.5271,
3,San Miguel,SV,82.06,few clouds,13.4833,-88.1833,
7,Zorritos,PE,73.69,broken clouds,-3.6805,-80.6782,
9,Rikitea,PF,74.03,overcast clouds,-23.1203,-134.9692,
12,Georgetown,MY,82.33,few clouds,5.4112,100.3354,
13,Atuona,PF,76.87,light rain,-9.8000,-139.0333,
15,Cabedelo,BR,74.07,broken clouds,-6.9811,-34.8339,
18,Touros,BR,73.60,few clouds,-5.1989,-35.4608,
19,Port-Gentil,GA,75.07,overcast clouds,-0.7193,8.7815,

In [21]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.
for index, row in hotel_df.iterrows():
    # 6c. Get latitude and longitude from DataFrame
    lat = row['Lat']
    lng = row['Lng']
    params['location'] = f"{lat},{lng}"
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = 'https://maps.googleapis.com/maps/api/place/nearbysearch/json'

    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels['results'][0]['name']
    except (IndexError):
            print("Hotel not found... skipping")

Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping

In [22]:
# 7. Drop the rows where there is no Hotel Name.
hotle_df = hotel_df.dropna()
hotel_df

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
1,Mozarlandia,BR,71.80,clear sky,-14.7447,-50.5706,Hotel Santa MÃ´nica
2,Avera,US,81.91,broken clouds,33.1940,-82.5271,
3,San Miguel,SV,82.06,few clouds,13.4833,-88.1833,Excalibur
7,Zorritos,PE,73.69,broken clouds,-3.6805,-80.6782,Hotel Pinamar
9,Rikitea,PF,74.03,overcast clouds,-23.1203,-134.9692,People ThankYou
...,...,...,...,...,...,...,...
210,Maragogi,BR,71.98,broken clouds,-9.0122,-35.2225,Salinas do Maragogi All Inclusive Resort
211,Cururupu,BR,73.96,scattered clouds,-1.8283,-44.8683,POUSADA TRAVÃ‰S'CIA
212,Coahuayana,MX,79.59,overcast clouds,18.7333,-103.6833,El rranchito michuacan de ocampos
213,Nova Olimpia,BR,73.45,clear sky,-14.7972,-57.2881,Motel glamour
217,Aracati,BR,78.19,overcast clouds,-4.5617,-37.7697,Hostel Pousada Ibiza

In [29]:
# 8a. Create the output File (CSV)
output_data_file = "../Vacation_Search/WeatherPy_vacation.csv"
# 8b. Export the City_Data into a csv
hotel_df.to_csv(output_data_file, index_label="City_ID")

In [30]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description} and {Max Temp} Â°F</dd>
</dl>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = hotel_df[["Lat", "Lng"]]

In [31]:
# 11a. Add a marker layer for each city to the map. 
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)

# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))